### ISSUE TITLE
Filters from list and regex are not all matched

### ISSUE THREAD

**Issue by jouir** [jouir/pgterminate#2]
With this list of session.Users:
  - test
  - test_1
  - test_2
  - postgres

And this configuration:
```yaml
include-users:
  - test
include-users-regex: '^test_[0-9]$'
```

Users `test`, `test_1` and `test_2` should be included, but only `test` is.

Same for exclude filters:
```yaml
exclude-users:
  - test
exclude-users-regex: '^test_[0-9]$'
```

Should include `postgres` but includes `test_1`, `test_2` and `postgres`.

Version:
```
pgterminate version 1.0.0-763359c (compiled with go1.18.1)
```
